## *RaschPy* simulation functionality

This notebook works through examples of how to generate simulated data sets with `RaschPy` for experimental use where knowledge of the underlying 'ground truth' of the generating parameters is useful, for example when comparing the efficacy of different estimation algorithms, such as in Elliott & Buttery (2022a) or exploring the effect of fitting different Rasch models to the same data set, such as in Elliott & Buttery (2022b). There are separate classes for each model: `SLM_Sim` for the simple logistic model (or dichotomous Rasch model) (Rasch, 1960), `PCM_Sim` for the partial credit model (Masters, 1982), `RSM_Sim` for the rating scale model (Andrich, 1978), `MFRM_Sim_Global` for the many-facet Rasch model (Linacre, 1994), and the family of extended MFRMs (Elliott 2025, Elliott & Buttery, 2022b): `MFRM_Sim_Items` for the vector-by-item extended MFRM , `MFRM_Sim_Thresholds` for the vector-by-threshold extended MFRM, `MFRM_Sim_Matrix` for the matrix extended MFRM, and `MFRM_Sim_Bivector` for the bivector extended MFRM. All data is generated to fit the chosen model.

**References**

&nbsp;&nbsp;&nbsp;&nbsp; Andrich, D. (1978). A rating formulation for ordered response categories. *Psychometrika*, *43*(4), 561–573.

&nbsp;&nbsp;&nbsp;&nbsp;   Elliott, M. (2025). Extended many-facet Rasch models: Accounting for rater effects in automated essay scoring systems [Apollo - University of Cambridge Repository]. https://doi.org/10.17863/CAM.127567

&nbsp;&nbsp;&nbsp;&nbsp; Elliott, M., & Buttery, P. J. (2022a) Non-iterative Conditional Pairwise Estimation for the Rating Scale Model, *Educational and Psychological Measurement*, *82*(5), 989-1019.

&nbsp;&nbsp;&nbsp;&nbsp; Elliott, M. and Buttery, P. J. (2022b) Extended Rater Representations in the Many-Facet Rasch Model, *Journal of Applied Measurement*, *22*(1), 133-160.

&nbsp;&nbsp;&nbsp;&nbsp; Linacre, J. M. (1994). *Many-Facet Rasch Measurement*. MESA Press.

&nbsp;&nbsp;&nbsp;&nbsp; Masters, G. N. (1982). A Rasch model for partial credit scoring. *Psychometrika*, *47*(2), 149–174.

&nbsp;&nbsp;&nbsp;&nbsp; Rasch, G. (1960). *Probabilistic models for some intelligence and attainment tests*. Danmarks Pædagogiske
Institut.

Import the packages and set the working directory (here called `my_working_directory`) - you will save your output files here.

In [1]:
import raschpy as rp
import numpy as np
import pandas as pd
import os

os.chdir('my_working_directory')

### `PCM_Sim`

Create an object `pcm_sim_1` of the class `PCM_Sim` with randomised central item difficulties/thresholds and person abilities. `PCM_Sim` will do this automatically when you pass `item_range`, `category_base`, `max_disorder`, `person_sd` and `offset` arguments to the simulation: item difficulties will be sampled from a uniform distribution and person abilities will be sampled from a normal distribution. We pass `item_range=4` to have items covering a range of 4 logits, and `person_sd=2` and `offset=1` to have a sample of persons with a mean ability 1 logit higher than the items, with a standard deviation of 2 logits. We also pass the additional arguments `category_base=1.5` and `max_disorder=1`; this sets the base category width to 1.5 logits, with a degree of random uniform variatoin around  controlled by `max_disorder`. With `max_disorder=1`, the minimum category width is 1 logit (and the maximum, symmetrically, will be 2 logits); a smaller value permits more variation in category widths, and a negative value for `max_disorder` allows the presence of disordered thresholds (hence the name of the argument). From this, a set of central item locations are generated from `item_range`, and sets of centred Rasch-ANdrich thresholds, each summing to zero, are generated from  `category_base` and `max_disorder`. One other additional argument that must be passed to `PCM_Sim` is `max_score_vector`, which is a list containing the maximum possible score for each item (this can vary from item to item). There are 5,000 persons and 12 items, with no missing data for this simulation.

In [2]:
pcm_sim_1 = rp.PCM_Sim(no_of_items=12,
                       no_of_persons=5000,
                       max_score_vector=[3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5],
                       item_range=4,
                       category_base=1.5,
                       max_disorder=1,
                       person_sd=2,
                       offset=0.5)

Save the generated response dataframe, which is stored as an attribute `pcm_sim_1.responses`, to file, and view the first 5 lines.

In [3]:
pcm_sim_1.responses.to_csv('pcm_sim_1_responses.csv')
pcm_sim_1.responses.head()

,Item_1,Item_2,Item_3,Item_4,Item_5,Item_6,Item_7,Item_8,Item_9,Item_10,Item_11,Item_12
Person_1,1,3,3,0,3,3,3,4,3,2,2,2
Person_2,1,3,3,2,3,3,5,5,4,3,5,2
Person_3,0,0,2,1,2,2,3,3,2,1,4,2
Person_4,3,3,3,3,3,3,5,5,4,5,5,3
Person_5,0,2,1,1,1,1,1,2,1,2,2,0

Save the generating item, threshold and person parameters to file, and view the first 5 lines of the item difficulties and the person locations, plus the DataFrame of centred Rasch-Andrich thresholds (items x threshold index, NaN-padded for items with a lower max score).

In [4]:
pcm_sim_1.items.to_csv('pcm_sim_1_items.csv', header=None)
pcm_sim_1.items.head()

Item_1    1.352695
Item_2   -0.957677
Item_3   -1.377819
Item_4    0.318326
Item_5   -1.870471
dtype: float64

In [5]:
pcm_sim_1.thresholds.to_csv('pcm_sim_1_thresholds.csv')
pcm_sim_1.thresholds

                0         1         2         3         4
Item_1  -1.179956  0.010448  1.169509       NaN       NaN
Item_2  -1.337160 -0.141680  1.478840       NaN       NaN
Item_3  -1.515116 -0.021499  1.536615       NaN       NaN
Item_4  -1.068521  0.005035  1.063486       NaN       NaN
Item_5  -1.886840  0.014422  1.872418       NaN       NaN
Item_6  -1.443590 -0.225139  1.668729       NaN       NaN
Item_7  -2.771115 -1.049404  0.118396  1.234736  2.467387
Item_8  -2.706254 -1.369192 -0.085590  1.558314  2.602723
Item_9  -2.693241 -1.480002 -0.345238  1.539532  2.978949
Item_10 -3.056906 -1.939538 -0.018639  1.638613  3.376469
Item_11 -3.136231 -1.416559 -0.166019  1.576841  3.141968
Item_12 -3.217645 -1.624530  0.152188  1.630768  3.059219

In [6]:
pcm_sim_1.persons.to_csv('pcm_sim_1_persons.csv', header=None)
pcm_sim_1.persons.head()

Person_1    0.870897
Person_2    2.823020
Person_3   -1.433158
Person_4    3.574533
Person_5   -1.117458
dtype: float64

Save the dictionary of uncentred thresholds to file and view.

In [7]:
pcm_sim_1.thresholds_uncentred.to_csv('pcm_sim_1_thresholds_uncentred.csv')
pcm_sim_1.thresholds_uncentred

                0         1         2         3         4
Item_1   0.172739  1.363143  2.522204       NaN       NaN
Item_2  -2.294837 -1.099357  0.521164       NaN       NaN
Item_3  -2.892936 -1.399319  0.158796       NaN       NaN
Item_4  -0.750196  0.323360  1.381812       NaN       NaN
Item_5  -3.757311 -1.856048  0.001947       NaN       NaN
Item_6  -2.481173 -1.262723  0.631145       NaN       NaN
Item_7  -2.884588 -1.162878  0.004923  1.121263  2.353914
Item_8  -4.758828 -3.421766 -2.138164 -0.494260  0.550149
Item_9  -1.194487  0.018752  1.153517  3.038286  4.477704
Item_10 -1.828385 -0.711017  1.209882  2.867134  4.604990
Item_11 -3.501368 -1.781696 -0.531156  1.211704  2.776831
Item_12 -1.270219  0.322897  2.099614  3.578194  5.006646

View `max_score_vector`.

In [8]:
pcm_sim_1.max_score_vector

Item_1     3
Item_2     3
Item_3     3
Item_4     3
Item_5     3
Item_6     3
Item_7     5
Item_8     5
Item_9     5
Item_10    5
Item_11    5
Item_12    5
dtype: int64

Create an object `pcm_1` of the class `PCM` from the response dataframe for analysis. The new object `pcm_1` automatically inherits all the parameters from `pcm_sim_1`, storing them under a namespace `.generating`.

In [9]:
pcm_1 = rp.PCM(pcm_sim_1)

You may wish to create a simulation based on specified, known item difficulties and/or person locations. This may be done by passing lists to the `manual_items`, `manual_thresholds` and/or `manual_persons` arguments (in which case, there is no need to pass the relevant `item_range`, `category_base`, `max_disorder`, `person_sd` or `offset` arguments). You may also customise the names of the items and/or persons by passing lists of the correct length to the manual_person_names and/or manual_item_names arguments.

The manual_items and manual_persons arguments may also be used to generate random item difficulties and/or person locations according to distributions other than the default uniform (for items) and normal (for persons). This is what is done in the example `pcm_sim_2` below: A set of specified, fixed item difficulties (4 items of difficulty between -1.5 logit and +1.5 logits with maximum scores of 3, 5, 5 and 3) and sets of Rasch-Andrich thresholds (each summing to zero) are passed together with a random uniform distribution of person locations between -2 and 2 logits. For this simulation, we also set a proportion of 20% missing data (missing completely at random) by passing the argument `missing=0.2`.

In [10]:
pcm_sim_2 = rp.PCM_Sim(no_of_items=4,
                       no_of_persons=1000,
                       max_score_vector=[3, 5, 5, 3],
                       missing=0.2,
                       manual_items= [-1.5, -0.5, 0.5, 1.5],
                       manual_thresholds=[[-1, 0, 1], [-2, -1, 0, 1, 2], [-2, -1, 0, 1, 2], [-1, 0, 1]],
                       manual_persons = np.random.uniform(-2, 2, 1000))

Save the generated response dataframe, which is stored as an attribute `pcm_sim_2.responses`, to file, and view the first 5 lines.

In [11]:
pcm_sim_2.responses

             Item_1  Item_2  Item_3  Item_4
Person_1        3.0     4.0     3.0     1.0
Person_2        3.0     3.0     2.0     0.0
Person_3        3.0     4.0     4.0     NaN
Person_4        2.0     NaN     2.0     0.0
Person_5        2.0     5.0     3.0     1.0
...             ...     ...     ...     ...
Person_996      3.0     4.0     NaN     0.0
Person_997      3.0     NaN     4.0     3.0
Person_998      3.0     NaN     NaN     0.0
Person_999      3.0     2.0     3.0     1.0
Person_1000     2.0     2.0     NaN     1.0

[1000 rows x 4 columns]

Save the generating item, threshold and person parameters to file, and view the item difficulties and the person locations, plus the DataFrame of centred Rasch-Andrich thresholds.

In [12]:
pcm_sim_2.items.to_csv('pcm_sim_2_items.csv', header=None)
pcm_sim_2.items

Item_1   -1.5
Item_2   -0.5
Item_3    0.5
Item_4    1.5
dtype: float64

In [13]:
pcm_sim_2.thresholds.to_csv('pcm_sim_2_thresholds.csv')
pcm_sim_2.thresholds

          0    1    2    3    4
Item_1 -1.0  0.0  1.0  NaN  NaN
Item_2 -2.0 -1.0  0.0  1.0  2.0
Item_3 -2.0 -1.0  0.0  1.0  2.0
Item_4 -1.0  0.0  1.0  NaN  NaN

In [14]:
pcm_sim_2.persons.to_csv('pcm_sim_2_persons.csv', header=None)
pcm_sim_2.persons.head()

Person_1    0.654402
Person_2   -0.622245
Person_3   -0.190591
Person_4    0.009397
Person_5    1.704262
dtype: float64

Save the DataFrame of uncentred thresholds to file and view.

In [15]:
pcm_sim_2.thresholds_uncentred.to_csv('pcm_sim_2_thresholds_uncentred.csv')
pcm_sim_2.thresholds_uncentred

          0    1    2    3    4
Item_1 -2.5 -1.5 -0.5  NaN  NaN
Item_2 -2.5 -1.5 -0.5  0.5  1.5
Item_3 -1.5 -0.5  0.5  1.5  2.5
Item_4  0.5  1.5  2.5  NaN  NaN

View `max_score_vector`.

In [16]:
pcm_sim_2.max_score_vector

Item_1    3
Item_2    5
Item_3    5
Item_4    3
dtype: int64

Create an object, `pcm_2`, of the class `PCM` from the response dataframe for analysis.

In [17]:
pcm_2 = rp.PCM(pcm_sim_2)

The two `PCM` objects `pcm_1` and `pcm_2` are now available for analysis and, where appropriate, comparison of the recovered estmates with the generating estimates. See the example `PCM` notebook for details on how to run a `PCM` analysis.